#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
# Arguments (4) :
#+ the path to the filw to be transfered
#+ the IP of the server 
#+ the username that scp use to connect
#+ the path to the ssh private key

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
