#!/usr/bin/env bash
# installs nginx and configures it

cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80;
    server_name _;
    root /var/www/html;

    location / {
        index index.html;
        echo "Hello World!";
    }
}
EOF

# Restart Nginx
service nginx restart