#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes.

h=0

while [ $h -lt 12 ]
do
    echo "Hour: $h"
    for m in {0..59}
    do
        echo "$m"
    done
    ((h++))
done

echo "Hour: $h"
for m in {0..59}
do
    echo "$m"
done
